//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhap
    {
        public int MaPhieu { get; set; }
        public int MaHang { get; set; }
        public Nullable<long> SoLuong { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
