//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        public ChucVu()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int MaChucVu { get; set; }
        public string ChucVu1 { get; set; }
        public Nullable<int> QuyenTruyCap { get; set; }
    
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
