//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int MaDon { get; set; }
        public Nullable<int> MaKh { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
