//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiHang
    {
        public LoaiHang()
        {
            this.HangHoas = new HashSet<HangHoa>();
        }
    
        public int MaLoai { get; set; }
        public string DienGiai { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<HangHoa> HangHoas { get; set; }
    }
}
