//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySieuThi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.ChiTietNhaps = new HashSet<ChiTietNhap>();
        }
    
        public int MaPhieu { get; set; }
        public string MaHienThi { get; set; }
        public Nullable<int> MaNv { get; set; }
        public Nullable<int> MaDoiTac { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<decimal> TienHang { get; set; }
        public Nullable<decimal> ChietKhau { get; set; }
        public Nullable<decimal> ThueVat { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<bool> Status { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTietNhap> ChiTietNhaps { get; set; }
        public virtual DoiTac DoiTac { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
